# Generated by Django 5.1 on 2025-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_quiz_max_score_quiz_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
